### PR TITLE
fix(preset-mini): remove units about `0` and `none` (#2153)close https://github.com/unocss/unocss/issues/2152

### LINKED ISSUE #2152: `inset-0` give `inset: 0rem` instead of `inset: 0`
Interactive docs: https://uno.antfu.me/?s=inset-0

image

### PR DESCRIPTION
**Pull request by zyyv**
close #2152

### CODE REVIEW

File: packages/preset-mini/src/_theme/misc.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export const spacing = {
 
 export const duration = {
   DEFAULT: '150ms',
-  none: '0ms',
+  none: '0',
```
Comment (sibbng) [inline packages/preset-mini/src/_theme/misc.ts:36]:
```suggestion
  none: '0s',
```

0 is not a valid duration
image

**Review by sibbng — CHANGES_REQUESTED** [review]

**Review by chu121su12 — APPROVED** [review]

**Review by Hongbusi — APPROVED** [review]
