### PR TITLE
fix(vscode): respect `unocss.root`

### LINKED ISSUE #1183: [vscode-intelisence] incorrectly detects typescript class as CSS
In a project I have code similar to the following, `static` is being detected by `UnoCSS`.

```ts
export class UserService {
    static async findById(id: string) {
        console.log(id);
    }
}
```

image
image

### PR DESCRIPTION
**Pull request by holazz**
After v0.40.0, configuring `unocss.root` does not work, decorations and tooltips are displayed in all files.

close #1183

### CODE REVIEW

**Comment by TrickyPi** [comment]
I guess the real issue in here
https://github.com/unocss/unocss/blob/main/packages/vscode/src/index.ts#L22toL28

the `registerAutoComplete` and `registerAnnotations` function always be called , even though the project does not contain any unocss config files, and the `ContextLoader` would create a default context.

**Comment by holazz** [comment]
Hi, @TrickyPi  thanks for your comment. I updated a commit. The extension shouldn't be activated when the config file is not found under `unocss.root`, right?

This is my first PR on `unocss` and my changes may be ill-considered. Hope someone more experienced can fix it if I'm in the wrong direction.

File: packages/vscode/src/annotation.ts [hunk 1]
```diff
@@ -53,9 +53,11 @@ export async function registerAnnotations(
       if (!doc)
         return reset()
 
-      const code = doc.getText()
       const id = doc.uri.fsPath
+      if (!id.startsWith(cwd))
```
Comment (TrickyPi) [inline packages/vscode/src/annotation.ts:57]: I guess it's unnecessary.

File: packages/vscode/src/autocomplete.ts [hunk 2]
```diff
@@ -64,9 +65,11 @@ export async function registerAutoComplete(
 
   const provider: CompletionItemProvider<UnoCompletionItem> = {
     async provideCompletionItems(doc, position) {
-      const code = doc.getText()
       const id = doc.uri.fsPath
+      if (!id.startsWith(cwd))
```
Comment (TrickyPi) [inline packages/vscode/src/autocomplete.ts:69]: As above.

File: packages/vscode/src/index.ts [hunk 3]
```diff
@@ -19,12 +19,17 @@ export async function activate(ext: ExtensionContext) {
   log.appendLine(`UnoCSS for VS Code  v${version} ${process.cwd()}`)
 
   const contextLoader = new ContextLoader(cwd)
+
+  const hasConfig = await contextLoader.loadContextInDirectory(cwd)
+  if (!hasConfig)
```
Comment (TrickyPi) [inline packages/vscode/src/index.ts:24]: The `load` function in `loadContextInDirectory` may be called twice, because `new ContextLoader` calls loadContextInDirectory by default, so it's better to call `contextLoader.loadContextInDirectory` after `contextLoader.ready`, and this call will hit the `contextsMap` cache (the cache value is `null`)

**Review by TrickyPi — COMMENTED** [review]
These are my ideas.

**Comment by TrickyPi** [comment]
> The extension shouldn't be activated when the config file is not found under `unocss.root`, right?

Yes

**Review by antfu — APPROVED** [review]

**Review by antfu — APPROVED** [review]
