### PR TITLE
fix: user config theme breakpoints order

### LINKED ISSUE #778: Breakpoint variants are not sorted properly
Config:
```ts
unocss.config.ts
export default defineConfig({
...
  theme: {
    breakpoints: {
      'xs': '320px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'xxl': '1536px',
    },
...
})
```

HTML code:
```html
<template>
  <div class="grid xs:grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
    <Item v-for="(item, index) in products" :key="index" :item="item" />
  </div>
</template>
```

Result:
image

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYcKALwAic5QDuARhkXzW7UqSsCtWou3AA9OAhnHQDMXHxjM0sbeylHWQAhMixOAGsABxYwUlooJNpUDD8AoOUQtIBPCTioHFoeAHMyMBBCFhRaOAAmOjUGppaCNo6AZnUQPubW9skoFHqJgaGjIsgS3SgCFE5PC0bmmrq9xenu2l6jqZGxhcuZuZvB6cMnbxdg1dsVwNe33VlP-yrH4uP4A4rAnzFMFAt6Qj5fEogqEIiHvQLQ74gwGYuHQFhpYZSUIGOY2QlEtS2RFQAAqMA4WVoGEEGCg4hAWA0xBAUAAghgWGowAQoABhADK4qgJHqWSwADofiikao1N0qDQAFZIJlgBDlQgkcjE-CdExsglEmAsCBYMgWfEADikL1hwE4qKgYEInDIACNxCgWPUWHBZRgYEg-Z79PgsvSmhhPTAkggLDAMBg0nVfL5w5G-fLBmpfG4WB5aKX3J5zDHffUsBgLAB9P1bYgpWuw2R%2BTRK7HOFFDkKcP20NpIbBQAOZwVGXJgeoZuBE6gIfBE2OG0h2i2EskyZzszmCHkAdq9QmZpCgF%2BQaHKGx1AqFAC9R9R5AigA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA752BjAAFqggqDrKhnAARp7CANaQ2DDaiAYxtLwc7gDMAEwADGC89pmGtKwgtO4AbAAsJWVBMaq0IN7uAOx1AByl5W10YkS1dACMRQUNg61t2WLjtBMFfc1DCwW8S%2B4TAKx5dXMV7bw7ywdHJzGk86ScpACUQA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

xs breakpoint has the highest priority with the lowest value

UPD: If i will add custom breakpoints with same values, then the order becomes correct

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYcKALwAic5QDuARhkXzW7UqSsCtWou3AA9OAhnHQDMXHxjM0sbeylHWQAhMixOAGsABxYwUlooJNpUDD8AoOUQtIBPCTioHFoeAHMyMBBCFhRaOAAmOjUGppaCNo6AZnUQPubW9skoFHqJgaGjIsgS3SgCFE5PC0bmmrq9xenu2l6jqZGxhcuZuZvB6cMnbxdg1dsVwNe33VlP-yrH4uP4A4rAnzFMFAt6Qj5fEogqEIiHvQLQ74gwGYuF6MJGEyOaIOSyyADCSFoGBYvRR60221ou36UDSMDYWAeS26bM4ACNqBgudNRhh%2BYLhR0JLNOGlqWlJUYXrC0f8USrSvDsYjcWrtajNej1SrQcbYab9RqLeCsTbcVAWGlhlJQgY5jZnS61LYdQAVGAcLJUwQYB3EOAgLAaYggKAAQWpajABCgZIAymmoCR6lksAA6H5mw3qbpUGgAK0pogQ5UIJHIrvwnRMDqdLvZECwZAsjoAHFJlb9OAawIROGQ%2BeIUCx6iw4DmMDAkHyDfp8FkA00MAaYEkEBYYBgMGk6r5fAul3y84M1L43CwPLQ7%2B5POZV%2BP6lgMBYAPoCwQpG%2BsKyH4miFpayj6nSIT8rQbRINgUCTkeNJGLkYD1IecAutQCD4C6a51qQXats6HoyM44iRtGsYAO1QEGYqkFA9HIGg5QbFWNJgAAXuKWDyAiQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA752BjAAFqggqDrKhnAARp7CANaQ2DDaiAYxtLwc7gDMAEwADGC89pmGtKwgtO4AbAAsJWVBMaq0IN7uAOx1AByl5W10YkS1dACMRQUNg61t2WLjtBMFfc1DCwW8S%2B4TAKx5dXMV7bw7ywdHJ8NgIQSRdIUb8zF3wrE2MPVNN20wHy%2BPX6fxiYmEYHMYD201mLVOQlYiShezWLwRIWQe0Ox3hMVI81InFIAEogA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

### PR DESCRIPTION
**Pull request by userquin**
This PR fix the breakpoints from user config theme:
- ~~`generator`: add resolve breakpoints utilities~~ => moved to `src/utils/utilities` on `preset-mini` 
- `preset-mini`: size and breakpoints
- `preset-wind`: container
- test: transformer-directive.test.ts (check last test `custom breakpoints` with custom generator)
- add `@unocss/preset-typography` to root `tsconfig.json`

**This PR doesn't solve the order problem, maybe we should document it or try to fix it later.**

closes #778

### CODE REVIEW

File: packages/core/src/generator/index.ts [hunk 1]
```diff
@@ -17,6 +17,28 @@ export class UnoGenerator {
...
+    if (this.userConfig && this.userConfig.theme)
+      breakpoints = (this.userConfig.theme as any).breakpoints
+
+    if (!breakpoints && this.config.theme)
+      breakpoints = (this.config.theme as any).breakpoints
+
+    return breakpoints
+  }
+
+  resolveVerticalBreakpoints() {
```
Comment (antfu) [inline packages/core/src/generator/index.ts:31]: Those two should belong to preset-mini instead of core. The core should be agnostic to how the theme object has been defined.

**Review by antfu — DISMISSED** [review]
