### PR TITLE
fix(webpack): escape backslash in css

### LINKED ISSUE #2794: (@unocss/webpack): class util with variant prefixes in webpack preset does not work
### UnoCSS version

0.53.3

### Describe the bug

Class util like `sm:bg-red-500` does not work in  webpack project with `@unocss/webpack`
```html
<template>
  <div class="flex justify-center">
    <p class="sm:bg-red-500">The background should be red but it does not</p>
  </div>
</template>
```
The style append to body is
```css
@media (min-width: 320px) {.sm:bg-red-500{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity))} }
```

The expected css result is 
```css
@media (min-width: 320px) { .sm\:bg-red-500{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity))} }
```
Maybe something got wrong when write to webpack assets without further escape for the generated css 

### Reproduction

- git clone [repo](https://github.com/zoeyzhao19/unocss-webpack-issue) or view online [sandbox](https://codesandbox.io/p/github/zoeyzhao19/unocss-webpack-issue/master?workspaceId=8a7a8b86-fa11-43ae-9a2d-fc45b02e677c)
-  run `pnpm dev` 

### System Info

- OS: Windows 10 10.0.22621

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by chu121su12**
Close #2794

### CODE REVIEW

File: packages/webpack/src/index.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export default function WebpackPlugin<Theme extends object>(
                   : (result.getLayer(layer) || '')
 
                 if (!quote)
-                  return css
+                  return css.replaceAll(/\\/g, '\\\\\\\\')
```
Comment (antfu) [inline packages/webpack/src/index.ts:121]: Why do we need so many slashes?

Comment (chu121su12) [reply packages/webpack/src/index.ts:121]: I'm not sure but I'm not good with webpack. I found this with trial and error. So if somebody have better webpack-fu, please advice. Having said that, dumping this `RawSource`:

https://github.com/unocss/unocss/blob/5d0a295860edc6c905af831b29ef9050f73086ff/packages/webpack/src/index.ts#L131

We can look for the output which is something like this:
```js
eval(
  /*v this is one single string to be eval-ed,  
       v with inlined backtick */
    "<... webpack content ...>
     ___CSS_LOADER_EXPORT___.push([
       module.id,
       `<... unocss' css in backtick ...>`,
       \"\"]);
    <... more webpack content ...>")
```
I hope you can see where this is going.

The css in the backtick (after this PR) already be outputted as 4x `\`:
image

And my guess is within the 2 quotes, the outer string ("") and the inner literal (\`\`), all the backslashes were reduced down to single `\` for output.

I think more escaping needs to be done with the quoted branch, but let's wait for issue or reproduction.
https://github.com/unocss/unocss/blob/5d0a295860edc6c905af831b29ef9050f73086ff/packages/webpack/src/index.ts#L120-L128

**Comment by chu121su12** [comment]
@high1 please provide issue & reproduction. thank you
