### PR TITLE
fix(postcss): ignore dot folders

### LINKED ISSUE #2473: When unocss is used as a postcss plugin, it causes "wait - compiling..." for nextjs.
### UnoCSS version

0.50.8

### Describe the bug

I tried postcss plugin for UnoCSS according to the [documentation](https://unocss.dev/integrations/postcss).

* UnoCSS only works at startup. HMR gets stuck with "wait - compiling...".
* And in globals.css, Tips "Unknown at-rule ".

### Reproduction

https://stackblitz.com/edit/nextjs-dfibap

### System Info

NextJS version: `13.3.0`
Node version: `v18.12.1`
OS: `Windows 11 22H2`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sibbng**
Fixes #2473

In this case, the `.next` folder had a few large `js` files causing the slowdown. IMO ignoring all dot folders by default is fine.

### CODE REVIEW

File: packages/postcss/src/index.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ function unocss(options: UnoPostcssPluginOptions = {}) {
           cwd,
           dot: true,
```
Comment (antfu) [inline packages/postcss/src/index.ts:119]: Should we just update this?
