### PR TITLE
fix(transformer-directive): support presetWind4 in `@screen` transformer

### LINKED ISSUE #4513: `presetWind4` breaks `@screen` with `transformerDirective`
### UnoCSS version

66.1.0-beta.5

### Describe the bug

Since the breakpoints are no longer part of the configuration the following code will not work when you use `transformerDirective` with `presetWind4`:

```css
<style>
@screen md {
   padding: 16px;
}
</style>
```

Not sure what's the workaround. I tried to:

```ts
// uno.config.ts
import { defineConfig, presetWind4 } from 'unocss'
import { breakpointsTailwind } from '@vueuse/core'
import transformerDirectives from '@unocss/transformer-directives'


export default defineConfig({
  presets: [presetWind4()],
  transformers: [transformerDirectives()]
  theme:{ breakpoints: breakpointsTailwind }
})
```

And then I get the following error: `[plugin:unocss:transformers:undefined] a[1].replace is not a function`.

## Workaround

Don't use the `@screen` transformer and use simply CSS

_I hope this kind of issues help to create a migration guide in the coming weeks, so people don't get surprises :)_

- Related: #4509 

### Reproduction

https://unocss.dev/play/#version=66.0.0&html=DwEwlgbgBAxgNgQwM5ILwCIC2BPAtPZJdAPgAkBTbAGihAHsoBJKACwQnKgSgAcERwAOwDmAfmAB6cBGIAoWUA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHHGFKgM6owDq2yAzCQFDkD0nFVtDTACzsAvnHRQIIOAHIArlggBjatRltQkWHBhQAhlmrpoIVFAAiwKkpjAAbjXGTpMgAILlqzroNGTZgFpkK1Qbexp1Nm44AEksXho6OAB3JjhBHQALYGo4HLgAI0kAa1QsNjZUAA8teDR0PTkAGzqMbDwCYgAKBA4E-moALjgAbT7ySkSBLBYugEp2ci4eSf5GGcF5xbgAXW2fQ2MoUygh0YO-Y7NLa1sHanmdthE5tiA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjoB6MiUCPRgOMxmFmI4oWXKtOjoJhG0jIww9E4a3YJyPmA5%2BYXFTBqCO3nH-QNAA&options=N4XyA

### System Info

N/A

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by onmax**
- closes #4513

`@screen md` with presetWind4 is broken.

I think renaming accessing to `breakpoint` is the easiest solution.

Please let me know what you think and whether you would prefer another solution.

---

As a workaournd, in my theme now I have this:  

```ts
import { theme } from '@unocss/preset-wind4/theme'
import transformerDirectives from '@unocss/transformer-directives'

export default defineConfig({
  preset: [presetWind4()],
  transformer: [transformerDirectives()],
  theme: { breakpoints: theme.breakpoint },
})
```

### CODE REVIEW

File: packages-presets/transformer-directives/src/screen.ts [hunk 1]
```diff
@@ -24,10 +25,10 @@ export function handleScreen({ code, uno }: TransformerDirectivesContext, node:
   const resolveBreakpoints = () => {
     let breakpoints: Record<string, string> | undefined
     if (uno.userConfig && uno.userConfig.theme)
-      breakpoints = (uno.userConfig.theme as Theme).breakpoints
+      breakpoints = (uno.userConfig.theme as Theme).breakpoints || (uno.config.theme as Theme).breakpoints
```
Comment (zyyv) [inline packages-presets/transformer-directives/src/screen.ts:28]: I don't think this is a safe way. I think you need to use the corresponding key name through the currently used preset

**Comment by onmax** [comment]
If I import `PRESET_NAME` from the `preset-wind4` package, I get this error: `Implicitly bundling "@unocss/preset-wind4/utils"` in the build. [See logs](https://github.com/unocss/unocss/actions/runs/15293452980/job/43017113626?pr=4681)

1. Should I add `@unocss/preset-wind4/utils` to `externals` in `build.config.ts`?

For now, I just copy/paste the name of the preset. Any other solution is welcomed!

**Review by zyyv — APPROVED** [review]
