### PR TITLE
fix(preset-wind): apply space/divide properly (#2150

### LINKED ISSUE #1246: unocss does not generate a proper selector for `children:space-y-2`
See the playground/html below. I expected all red squares to have space between them, but they do not. 
This did work in version v0.30.1. Somewhere between that version and v0.44.0 it broke

playground: https://uno.antfu.me/play/?html=DwEwlgbgBAxgFmANiATgUwHYC4DOAHAQxjQFoBPEgJgD4AoKKUSOhhp6AIwHMT0QSArAAYhUAO4kAjKLhSh1YAHpwEFq3ZRuvNP2GiJ0qLOkLlzeozOqL7NWxWaefQSPFyjc0yruMHW53puhsbySt42VnRhzEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wqgBdGTCkIA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA

###### HTML
```html
<div children:space-y-2>
  <div>
    <div bg-red-500 w-10 h-10></div>
    <div bg-red-500 w-10 h-10></div>
  </div>
  <div>
    <div bg-red-500 w-10 h-10></div>
    <div bg-red-500 w-10 h-10></div>
  </div>
</div>
```
###### config
```js
import {
  defineConfig,
  presetAttributify,
  presetUno
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify()
  ]
})

```

###### generated css:
```css
/* layer: default */
.w-10,
[w-10=""]{width:2.5rem;}
[h-10=""]{height:2.5rem;}
[children\:space-y-2=""]>:not([hidden])~:not([hidden])>*{--un-space-y-reverse:0;margin-top:calc(0.5rem * calc(1 - var(--un-space-y-reverse)));margin-bottom:calc(0.5rem * var(--un-space-y-reverse));}
.bg-red-500,
[bg-red-500=""]{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity));}
```

### LINKED ISSUE #2148: add prefix , variants not work
* no prefix , use `space-x`

image

* add prefix , space-x not work

image

> variantSpaceAndDivide not work

image

### PR DESCRIPTION
**Pull request by sibbng**
Fixes #2148
Fixes #1246

For output reference: https://play.tailwindcss.com/8hCO0cn404

### CODE REVIEW

File: packages/preset-wind/src/variants/misc.ts [hunk 1]
```diff
@@ -1,7 +1,11 @@
 import type { Variant } from '@unocss/core'
 
 export const variantSpaceAndDivide: Variant = (matcher) => {
-  if (/^space-?([xy])-?(-?.+)$/.test(matcher) || matcher.startsWith('divide-')) {
+  // test/svelte-scoped.test.ts:350:55
+  if (matcher.startsWith('_'))
+    return
+
+  if (/space-?([xy])-?(-?.+)$/.test(matcher) || matcher.startsWith('divide-')) {
```
Comment (sibbng) [inline packages/preset-wind/src/variants/misc.ts:8]: Notice: leading `^` removed
