### PR TITLE
fix(preset-mini): data attributes with named groups

### LINKED ISSUE #4129: Named Group Data Selectors Not Working
### UnoCSS version

^0.62.3

### Describe the bug

While the recent fix addressed group-data selectors for unnamed groups, it appears that named group data selectors are still not functioning as expected in UnoCSS. This functionality works correctly in Tailwind CSS but fails in UnoCSS.

## Steps to Reproduce

1. Create a div with a named group class
2. Inside the div, create a span with a group-data selector referencing the named group
3. Apply a style change based on the data state

```html
<div class="group/named" data-state="open">
  <span class="group-data-[state=open]/named:text-red-400">
    hello
  </span>
</div>
```

## Expected Behavior

The text should turn red when the parent div has a data-state of "open".

## Actual Behavior

The text does not change color, and the CSS output for the group-data selector is empty.

## Reproduction

Tailwind Playground ([working correctly](https://play.tailwindcss.com/Tp6cqLbAIa))
UnoCSS Playground ([not working](https://unocss.antfu.me/play/?html=DwEwlgbgBCCGAusC0BnR8CmBeARAewAcMA7HKAYwBtYUVcBzAJzwFcCB6Y2AWwxBwB8AKChRQkCtVq4RUJqwJI4iJAG00CbIRIBdTjz4AuAEb0kTDCSGDMaYO3ARh9x0KA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHABuwqMGFYYrAFxwA2irgB6M3CJV6YALTJhMYXaMA6DwF19phSCfMABaoUACUcAC8AHyIpqrMBKzwUKhEfABKqKzi8BFw-jBBIW4FQQpm1hC2dgqOznYAOkZGAHpwngBUDZ6h%2Bgqt7R2hZqFxcMDocAoAhClpvJnZEuEpMPRQWPkBwVDcqvGJkk7CkXBzGVk5RgCMnm4pYGLCzKgAgmJi5UZN3Z4VADRwABEQNG%2BzgCSwSQhT3YWGEIFQp3OC0uEiMACZPGMxqt1ptlODVKUdoZmLDWPDEf8xqpWKgxKhmDBoIZWJEYgADNyVWxGAAkCDqwlInjggtYpE5NPBpFMcs8NNIoSAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA))

## Additional Context

This issue specifically pertains to named group data selectors. The fix for unnamed group data selectors appears to be working as expected.

### System Info

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sibbng**
Fixes #4129
Closes #4164

### CODE REVIEW

File: packages/preset-mini/src/_variants/data.ts [hunk 1]
```diff
@@ -25,11 +25,11 @@ function taggedData(tagName: string): Variant {
     match(matcher, ctx: VariantContext<Theme>) {
       const variant = variantGetParameter(`${tagName}-data-`, matcher, ctx.generator.config.separators)
       if (variant) {
-        const [match, rest] = variant
+        const [match, rest, label] = variant
         const dataAttribute = h.bracket(match) ?? ctx.theme.data?.[match] ?? ''
```
Comment (Simon-He95) [inline packages/preset-mini/src/_variants/data.ts:29]: image

I think this should be consistent with tailwind and the attributes should be wrapped in quotation marks.

Comment (Simon-He95) [reply packages/preset-mini/src/_variants/data.ts:29]: sure

**Review by Simon-He95 — APPROVED** [review]

**Review by antfu — APPROVED** [review]
