### PR TITLE
fix(preset-attributify): remove StringNumberComposition type for better perf

### LINKED ISSUE #3458: `AttributifyAttributes` cause vscode slow
### UnoCSS version

latest

### Describe the bug

When I save code for autoformat in vscode, It need a few seconds to save down when I use AttributifyAttributes.
```ts
declare module '@vue/runtime-core' {
  interface AllowedComponentProps extends AttributifyAttributes {
  }
}
```

### Reproduction

https://github.com/unocss/unocss/assets/32807958/399106dd-cfb0-4725-ba33-9ccdc97a0137

### System Info

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zhiyuanzmj**
closed #3458

https://github.com/unocss/unocss/assets/32807958/5c6d82a6-2287-450c-aeab-b7f98639e18e

### CODE REVIEW

File: packages/preset-attributify/src/jsx.ts [hunk 1]
```diff
@@ -113,6 +100,8 @@ export type SeparateEnabled =
   | 'justify'
   | 'list'
   | 'm'
+  | 'fw'
```
Comment (zyyv) [inline packages/preset-attributify/src/jsx.ts:103]: it needs to be in order.😅

Comment (zhiyuanzmj) [reply packages/preset-attributify/src/jsx.ts]: ok

**Review by antfu — APPROVED** [review]
