### PR TITLE
fix(vscode): fix custom theme colors display

### LINKED ISSUE #4786: vscode unocss extension not show correct color by wind4
### UnoCSS version

66.3.2

### Describe the bug

In the `uno.config.js`：
```ts
const UnoColors = { sb2: '#CDE8FF'  }

{
  theme: {
      colors: UnoColors
  }
}
```

in code，always show black point

Image

### Reproduction

this topics

### System Info

_No response_

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lzl0304**
Fixes #4786  Related #4653

### CODE REVIEW

**Comment by JunyWuuuu91** [comment]
Hello, could you expedite the review process? The issue is affecting my ability to determine whether the problem lies with my theme color variables not taking effect or some other error after coding. @zyyv

File: packages-integrations/vscode/src/utils.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import prettier from 'prettier/standalone'
 
 const remUnitRE = /(-?[\d.]+)rem(\s+!important)?;/
 const matchCssVarNameRE = /var\((?<cssVarName>--[^,|)]+)(?:,(?<fallback>[^)]+))?\)/g
-const cssColorRE = /(?:#|0x)(?:[a-f0-9]{3}|[a-f0-9]{6})\b|(?:(?:rgb|hsl)a?|oklch)?\(.*\)/g
+const cssColorRE = /(?:#|0x)(?:[a-f0-9]{3}|[a-f0-9]{6})\b|(?:rgb|rgba|hsl|hsla|oklch)\(.*\)/g
```
Comment (zyyv) [inline packages-integrations/vscode/src/utils.ts:9]: Is there any difference between this rewrite and the original one? It seems to be the same behavior

Comment (lzl0304) [reply packages-integrations/vscode/src/utils.ts:9]: The rewritten regex differs from the original. In the original, the `?` in `(?:rgb|hsl)a?|oklch)?` makes the prefix optional, allowing it to match any parenthetical content (e.g., `(foo)` or `()`). The rewritten version requires an explicit prefix (`rgb`, `rgba`, `hsl`,` hsla`, or `oklch`), making it stricter for CSS colors.

**Review by zyyv — APPROVED** [review]
Thank you. There is an extra question mark at the end of the regular expression.
